apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nova.cars.lab
  namespace: openshift-gitops
spec:
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - '*'
